### PR TITLE
Adding keyboard, interface selection & proper reportID support

### PR DESCRIPTION
**Pull request by RockyZeroFour**
- Adding a new detection mode setting for keyboard support
- Adding the support to select a specific interface number which should be scanned
- Fixed that only the packets of the reportID one is checked instead of the ID of the found function if report ID are present
- Correct usage of the current interface number for requests
- Displaying the connected device even when unsupported
- Better identification if a mouse or keyboard is currently searched
- The detection of a keyboard or mouse no longer depends if there is a corresponding HID boot interface present but rather relies on the selected detection mode and if the corresponding function was found during the parsing of the HID report descriptor

### CODE REVIEW

**Comment by RockyZeroFour** [comment]
I'm not sure if three key items are enough for the keyboard detection and so if that maybe limits which keys can be detected.

**Comment by maximevince** [comment]
Thank you for your contribution. I'll be looking into this soon!

**Comment by RockyZeroFour** [comment]
Ideally the enumeration would trigger again if the detection mode changes from keyboard to mouse or vice versa, or if the selected interface number is changed. Until then the device under test needs to be re-connected.

Also the numbers for the interface selection of the UI are added hard coded. Would be better if this list would be generated depending on the value of `USBH_MAX_NUM_INTERFACES`.

**Comment by maximevince** [comment]
I've merged this into a separate branch for now, to allow me to rework some of the code. Overall this looks great, thanks for your contribution!

**Comment by maximevince** [comment]
@RockyZeroFour I've been testing this on multiple keyboards. On some Logitech keyboard it got it to detect keypresses of the modifier keys (shift, alt, ...)
On a Wooting 60HE I have to manually select interface #3 for it to find a key offset, but after that it does not detect any keypresses.

Could you elaborate a bit on the way you intended the keyboard flow to work?

Thanks

**Comment by RockyZeroFour** [comment]
**How it works in general.**
The primary identification works for a boot interface. If a device has a keyboard interface which isn't specified as a boot interface the interface number needs to be selected manually. Then the report is scanned for either a mouse or a keyboard the same way when the interface is found automatically.

The goal of that update was to add generic keyboard support. Of course that it also works for the Wootings. 😄 But I haven't changed the way the detection works at all. So XLAT still has trouble with analog signal detection. So it's not intended to use XLAT directly connected to an analog signal.


**About the Wootings.**
For a Wooting either NKRO needs to be disabled in order that the boot keyboard on interface two (ID 1) work. Otherwise the fourth interface (ID 3) needs to be selected for the primary gaming keyboard.

I tested it on the physical buttons of a UwU so far (that has three analog keys as well as three traditional soft buttons). Checking directly the analog sensor of a Wooting don't make much sense because the key activation depends on the specific actuation point of the key under test. So the key activation would not be inline with the threshold XLAT used to determine the signal state. The current goal is to use a solenoid triggered by XLAT to start a keypress and to detect that instead of the key itself.

**We may later on use an additional device which would be able to overtaken the signal. The signal from XLAT itself isn't able to overcome the much stronger signal provided by the Hall effect sensor.**

**Comment by Rocky04** [comment]
There is a limitation, currently XLAT can only detect the modifier keys, like ctrl, alt, Win and shift.

**Pull request merged**
